spring:
  datasource:
    url: jdbc:postgresql://172.17.0.3:5432/selmag
    username: selmag
    password: selmag
  cache:
    cache-names: customer/product-categories/by-id
logging:
  level:
    sql: trace